version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "ch.qos.logback:logback-core"
      - dependency-name: "org.jetbrains.kotlin:kotlin-gradle-plugin"
