package ghistabs.integration

import ghidra.app.plugin.core.analysis.AutoAnalysisManager
import ghidra.app.util.importer.MessageLog
import ghidra.app.util.importer.ProgramLoader
import ghidra.app.util.opinion.LoadResults
import ghidra.program.database.data.DataTypeUtilities
import ghidra.program.model.address.Address
import ghidra.program.model.data.*
import ghidra.program.model.data.Array
import ghidra.program.model.data.Enum
import ghidra.program.model.listing.Function
import ghidra.program.model.listing.Program
import ghidra.test.AbstractGhidraHeadlessIntegrationTest
import ghidra.util.task.TaskMonitor
import ghistabs.*
import ghistabs.ImportOptions.Companion.OVERLAY_SECTION
import ghistabs.StabsAnalyzer.Companion.import
import ghistabs.audit.DemanglerWhitelist
import ghistabs.baseline.BaselineLoader
import ghistabs.baseline.BaselineWriter
import ghistabs.diagnose.CapturingSink
import ghistabs.diagnose.dumpJson
import ghistabs.diagnose.writeRegistryDump
import ghistabs.harvest.ContentIndex
import ghistabs.harvest.Type
import ghistabs.importer.*
import ghistabs.materialize.conflictCount
import ghistabs.materialize.itanium.Itanium
import ghistabs.materialize.itanium.hasPolymorphicBaseSubobject
import ghistabs.parse.*
import ghistabs.test.*
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.encodeToStream
import org.junit.jupiter.api.*
import org.junit.jupiter.api.Assumptions.abort
import org.junit.jupiter.api.Assumptions.assumeTrue
import org.junit.jupiter.api.io.TempDir
import java.io.File
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.writeText

/**
 * Execution-order mode for the regression harness.
 *
 * The behavior of StabsAnalyzer can differ depending on whether it runs as
 * part of Ghidra's auto-analysis pass (alongside the demangler, decompiler,
 * etc.) or strictly after it. Both modes are observed in practice (e.g. when
 * a user re-imports stabs from the Tools menu after an analysis has settled).
 *
 *  - [CONCURRENT]: our analyzer is left enabled in the analysis options. It is
 *    fired by `AutoAnalysisManager.startAnalysis` alongside the demangler.
 *    Symptom: many function names stay mangled (`_Z6encodeP6Buffer` and the like),
 *    presumably because the demangler runs later but skips symbols whose
 *    SourceType we've already promoted.
 *
 *  - [AFTER]: our analyzer is disabled in the analysis options before
 *    `startAnalysis` runs, so auto-analysis (demangler included) settles
 *    first. We then invoke StabsAnalyzer manually. Symptom seen here:
 *    `/Demangler/...` placeholder stubs created by Ghidra's demangler are
 *    sometimes not replaced (e.g. `/Demangler/bouniaf`) — this was
 *    a DemanglerReplacer candidate-filtering bug, see DemanglerReplacer.
 */
enum class Mode { BEFORE, CONCURRENT, AFTER }

/**
 * Regression test harness for StabsAnalyzer, one subclass per fixture × [Mode] (generated by
 * `:generateFixtureTests` from the corpus on disk). Runs the full analysis pipeline and validates
 * the materialized output plus the counters against the fixture's committed baseline.
 *
 * **Every assertion here is corpus-wide.** Nothing may be gated on `binaryName`, and nothing may
 * look up a class only one binary declares: an assertion keyed to a fixture stops running the
 * moment that fixture is not on disk, silently. Drive the check from [ImportArtifacts.harvest] /
 * [ImportArtifacts.registry] instead, assert over every instance of the shape, and `assumeTrue` on
 * the shape being present at all.
 *
 * A fixture that is absent skips its whole class.
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@Tag("integration")
abstract class StabsImportRegressionBase(val binaryName: String, val mode: Mode) :
    AbstractGhidraHeadlessIntegrationTest() {

    // Manual inputs live under src/test/resources/ (binaries — gitignored,
    // user-placed — and baselines — tracked); test-generated dumps go to
    // build/test-output/ so `./gradlew clean` regenerates them. See README
    // / build.gradle.kts for the split rationale.
    private fun outputFile(kind: String) = File("build/test-output/${kind}s/${fixture.nameWithoutExtension}-$kind.json")
    private val fixture get() = File("src/test/resources/binaries/$binaryName")
    private val baselineFile get() = File("src/test/resources/baselines/${fixture.nameWithoutExtension}-baseline.json")
    private val recordsFile get() = outputFile("record")
    private val emptyStubDumpFile get() = File(
        "build/test-output/demangler-empty-stubs/${fixture.nameWithoutExtension}.txt",
    )
    private val harvestFile get() = outputFile("harvest.${mode.name.lowercase()}")
    private val registryDumpFile get() = outputFile("registry.${mode.name.lowercase()}")
    private val degradationFile
        get() = File("build/test-output/degradations/${fixture.nameWithoutExtension}.${mode.name.lowercase()}.txt")
    private val logFile
        get() = File("build/test-output/logs/${fixture.nameWithoutExtension}.${mode.name.lowercase()}.log")
    private val analysisTimesFile
        get() = File("build/test-output/analysis-times/${fixture.nameWithoutExtension}.${mode.name.lowercase()}.txt")

    private lateinit var loadResults: LoadResults<Program>
    private lateinit var context: ImportContext<CapturingSink>
    private lateinit var artifacts: ImportArtifacts
    private val program get() = context.program

    @BeforeAll
    fun setUp() {
        assumeTrue(
            fixture.exists(),
            "Skipping: ${fixture.path} absent, must be added manually",
        )

        val log = MessageLog()
        val monitor = TaskMonitor.DUMMY
        logFile.parentFile.mkdirs()
        recordsFile.parentFile.mkdirs()
        harvestFile.parentFile.mkdirs()

        try {
            // Loading the raw binary is the ONLY legitimately-skippable step: a corrupt or
            // format-unsupported fixture is an environment problem, not a bug in our analyzer.
            // Everything after it is code under test and must fail loudly (see the catch below).
            loadResults = try {
                ProgramLoader.builder().source(fixture).compiler("gcc").log(log).monitor(monitor).load()
            } catch (e: Exception) {
                e.printStackTrace()
                abort("Skipping $binaryName: ProgramLoader could not load the fixture: $e")
            }

            context = loadResults.getPrimaryDomainObject(this).defaultContext()

            val mgr = AutoAnalysisManager.getAnalysisManager(program)
            val options = program.getOptions(Program.ANALYSIS_PROPERTIES)

            when (mode) {
                Mode.CONCURRENT -> {
                    // Confirm Ghidra's ClassSearcher actually discovered our analyzer
                    // (build/classes/kotlin/main is on the test classpath). If this
                    // assertion ever fails the test would be silently meaningless.
                    val discovered = mgr.getAnalyzer(StabsAnalyzer.NAME)
                    discovered.mustNotBeNull("StabsAnalyzer not discovered by ClassSearcher")
                    discovered.mustBeA<StabsAnalyzer>()

                    // Pre-build the test's context and install its CapturingSink as a
                    // side-channel on the Program. StabsAnalyzer.added() will tee its
                    // output to that sink in addition to Ghidra's truncating MessageLog,
                    // so we get the full, untruncated log here while autoanalysis still
                    // sees its own logs in MessageLog.
                    val probe = ImportProbe.install(context)

                    // BYTE_ANALYZER auto-fires on byte changes; on a freshly-loaded
                    // program nothing has "changed" since the loader put
                    // bytes down, so we explicitly schedule our analyzer for the
                    // next analysis pass — it then runs at its declared priority
                    // alongside the demangler.
                    // Sub-options writes hit the program options DB and need a transaction (as the
                    // AFTER branch's analyzer-disable does); the .stab overlay is a diagnostic view,
                    // not needed to produce types (~8% of the run), so skip it here too.
                    program.runTransaction("enable-stabs-analyzer") {
                        options.setBoolean(StabsAnalyzer.NAME, true)
                        options.getOptions(StabsAnalyzer.NAME)[OVERLAY_SECTION] = false
                    }
                    mgr.scheduleOneTimeAnalysis(discovered, program.memory)
                    runAutoAnalysis(mgr, monitor)
                    artifacts = checkNotNull(probe.artifacts) { "artifacts not populated by CONCURRENT" }
                }

                Mode.BEFORE -> {
                    // Just run our analyzer with no autoanalysis
                    program.runTransaction("stabs-analyze") {
                        artifacts = checkNotNull(context.import().artifacts) { "artifacts not populated by BEFORE" }
                    }
                }

                Mode.AFTER -> {
                    // Disable our analyzer so auto-analysis (incl. demangler) settles
                    // without us, then re-run it manually with our CapturingSink.
                    // `Options.setBoolean` mutates the program options DB and needs
                    // a transaction.
                    program.runTransaction("disable-stabs-analyzer") {
                        options.setBoolean(StabsAnalyzer.NAME, false)
                    }
                    mgr.initializeOptions()
                    runAutoAnalysis(mgr, monitor)
                    program.runTransaction("stabs-analyze") {
                        artifacts = checkNotNull(context.import().artifacts) { "artifacts not populated by AFTER" }
                    }
                }
            }
            // CapturingSink holds the full untruncated log in both modes
            // (in CONCURRENT it's fed via ExternalSinks → TeeSink). MessageLog
            // is appended for parity with Ghidra's own view, even though it
            // truncates at ~500 lines.
            logFile.writeText(context.terminal.dedupedOutput() + "\n--- MessageLog ---\n" + log.toString())
            // Stripped/no-stabs fixtures produce no artifacts; nothing to dump.
            artifacts.writeRegistryDump(registryDumpFile)
            writeDegradationDump()
        } catch (e: org.opentest4j.TestAbortedException) {
            throw e // the load-failure skip above — propagate as a skip, not a failure
        } catch (e: Exception) {
            // Load succeeded, so anything thrown here is a bug in our import / analysis / dump path.
            // Fail the invocation loudly (in this exact fixture×mode) instead of masking it as a skip:
            // silently swallowing crashes here is what let a TypeResolver NPE and a registry-dump
            // `.single()` crash hide for so long, and dropped whole AFTER-mode runs unnoticed.
            e.printStackTrace()
            throw AssertionError("setUp failed for $binaryName/$mode (import/dump, not fixture load): $e", e)
        }
    }

    private fun runAutoAnalysis(mgr: AutoAnalysisManager, monitor: TaskMonitor) {
        program.disableWindowsResourceAnalyzer()
        mgr.reAnalyzeAll(null)
        program.runTransaction("auto-analyze") {
            mgr.startAnalysis(monitor)
            mgr.waitForAnalysis(null, monitor)
        }
        // Ghidra's own per-analyzer wall times. The Gradle listener only reports whole-invocation
        // time, which also carries fixture load, our import and the dumps; this attributes the
        // analysis share to individual analyzers, so a perf change can be localized without a
        // profiler. Written per fixture×mode alongside the other dumps.
        analysisTimesFile.apply { parentFile.mkdirs() }
            .writeText("total = ${mgr.totalTimeInMillis} ms\n\n${mgr.taskTimesString}")
    }

    // The CLI's `--degradation-log` dump, grouped by category, so one integrationTest run emits the
    // full CLI dump set (records/harvest/registry already written above) without a separate probe pass.
    private fun writeDegradationDump() {
        val byCategory = context.diagnostics.snapshotDegradations()
            .groupBy { it.category }.toList().sortedByDescending { it.second.size }
        degradationFile.parentFile.mkdirs()
        degradationFile.writeText(
            buildString {
                appendLine("fixture: $binaryName ($mode)")
                appendLine("total degradations: ${byCategory.sumOf { it.second.size }}")
                appendLine("\ncounts by category:")
                byCategory.forEach { (cat, list) -> appendLine("  $cat = ${list.size}") }
                byCategory.forEach { (cat, list) ->
                    appendLine("\n=== $cat (${list.size}) ===")
                    list.forEach { appendLine("  ${it.detail}") }
                }
            },
        )
    }

    @AfterAll
    fun tearDown() {
        ImportProbe.clear(program)
        program.release(this)
        loadResults.close()
    }

    @Test
    fun countersWithinBaseline() {
        assumeTrue { mode == Mode.AFTER || mode == Mode.CONCURRENT }
        // Authoritative per-category counts. Not `log.tagFrequencies()`: that only sees categories
        // that reach the sink (record*/direct-inc bypass it) and ignores `count = n` tallies, which
        // made assertions on those categories (e.g. empty-scope) silently vacuous.
        val counters = context.diagnostics.snapshotCounters()

        // -PregenerateBaselines=true rewrites the baseline from the observed counts (deterministic
        // import). The resulting git diff is the record of exactly which counters moved. This has to
        // precede the exists() check below, or a newly added fixture can never get a first baseline:
        // the assumption skips the test before it can write one.
        if (System.getProperty("regenerateBaselines") == "true") {
            BaselineWriter.write(baselineFile, counters, "$binaryName - generated from snapshotCounters()")
            return
        }

        assumeTrue(baselineFile.exists(), "Skipping: no committed baseline for $binaryName")

        val baseline = BaselineLoader.load(baselineFile)

        // If no stabs were found in the binary, skip the test
        // (stabs sections may not exist or may be in a non-standard format)
        assumeTrue(
            counters.isNotEmpty(),
            "Skipping: No stabs counters found in binary (stabs sections absent or non-standard format)",
        )

        val drift = mutableListOf<String>()
        for ((counterName, range) in baseline.counters) {
            val actual = counters.getOrDefault(counterName, 0L)
            if (actual !in range.min..range.max) {
                drift += "Counter '$counterName' = $actual outside baseline range [${range.min}..${range.max}]"
            }
        }
        if (drift.isNotEmpty()) {
            Assertions.fail<Unit>("Baseline drift detected:\n  - " + drift.joinToString("\n  - "))
        }
    }

    /**
     * Every array global lands with the element count its stab declares. gcc encodes the count only
     * via the index Range (`ar(0,1);0;15;`), never as a length, and the old Array case bailed
     * whenever either the element Ref failed to resolve or the length was absent — leaving the
     * global untyped. [ghistabs.materialize.DataTypeRegistry] now derives the count from the Range and
     * falls back to Undefined1 elements.
     *
     * Driven from the harvest rather than a named symbol, so it covers every array global in every
     * fixture. Must hold in both modes: CONCURRENT races autoanalysis's `undefined4` placeholders,
     * which `applyGlobalOrStatic` evicts via `DataUtilities.CLEAR_ALL_CONFLICT_DATA`.
     */
    @Test
    @ExpectedToFail(
        fixtures = ["zlib_aout_gcc263.o", "tinyxml_aout_gcc295.o"],
        reason = "relocatable object (ld -r): sections sit at 0 unrelocated, so a global's stab value " +
            "resolves into a block with nothing applied at it — gcc 2.95's `__vt_<class>` vtables on " +
            "tinyxml are array globals and land there",
    )
    fun arrayGlobalsGetTheirDeclaredLength() {
        val declared = artifacts.harvest.staticsByCu.values.flatten()
            .mapNotNull { sym ->
                val elements = (resolve(sym.body.type) as? TypeDecl.Array)?.declaredElements ?: return@mapNotNull null
                val addr = context.resolver.buildAddress(sym.rawValue)
                Triple(sym.body.name, addr, elements).takeIf { program.memory.getBlock(addr) != null }
            }
        assumeTrue(declared.isNotEmpty(), "Skipping: no array globals with a declared extent")

        val applied = declared.mapNotNull { (name, addr, elements) ->
            (program.listing.getDataAt(addr)?.dataType as? Array)?.let { Triple(name, it, elements) }
        }
        val untyped = declared
            .filterNot { (_, addr, _) -> program.listing.getDataAt(addr)?.dataType is Array }
            .map { (n, a, _) -> "$n @ $a is ${program.listing.getDataAt(a)?.dataType?.name}" }
        val wrong = applied.filter { (_, arr, elements) -> arr.numElements.toLong() != elements }
            .map { (name, arr, elements) -> "$name: ${arr.numElements} elements, stab says $elements" }
        // The count is only half of it: the old Array case also bailed when the element Ref failed to
        // resolve, and `Undefined1` elements are the fallback that silently hides that. An element the
        // stab names as an aggregate or enum must come through as one.
        val undefinedElements = declared.mapNotNull { (name, addr, _) ->
            val declaredElement = (
                resolve(
                    artifacts.harvest.staticsByCu.values.flatten()
                        .first { it.body.name == name }.body.type,
                ) as? TypeDecl.Array
                )?.element
            val named = (resolve(declaredElement ?: return@mapNotNull null) as? TypeDecl.Struct) != null ||
                (resolve(declaredElement) as? TypeDecl.Enum) != null
            val applied = program.listing.getDataAt(addr)?.dataType as? Array ?: return@mapNotNull null
            "$name: elements are ${applied.dataType.name}".takeIf { named && applied.dataType is Undefined }
        }
        assertAll(
            {
                untyped.sorted().take(
                    10,
                ).mustBeEmpty("${untyped.size} of ${declared.size} declared array globals never became an Array")
            },
            {
                wrong.take(10).mustBeEmpty("${wrong.size} of ${applied.size} array globals lost their declared extent")
            },
            {
                undefinedElements.take(
                    10,
                ).mustBeEmpty("${undefinedElements.size} array globals fell back to Undefined elements")
            },
        )
    }

    /**
     * The program's line map is the harvest's, entry for entry: [ghistabs.importer.SourceMapApplier]
     * counts what it should hold from the parsed entries (distinct after the §15 fold, minus the ones
     * it reported dropping), and the database is read back to see that it does. An entry lost to a
     * silently-swallowed rejection shows up here as a shortfall.
     *
     * Both counters, because the applier writes two kinds of entry onto the one manager: the
     * zero-length N_SLINE points and the ranged N_SO/N_SOL text partition.
     *
     * Also the fold's own contract: a spelling folded away keeps its `SourceFile`, with no entries.
     */
    @Test
    fun programLineMapMatchesHarvest() {
        val folds = artifacts.index.renderIdentityBySource
        assumeTrue(folds.isNotEmpty(), "Skipping: no N_SLINE entries in this binary")
        val manager = program.sourceFileManager
        val counters = context.diagnostics.snapshotCounters()
        val expected = counters.getOrDefault("sourcemap-entries", 0) + counters.getOrDefault("textrange-entries", 0)

        manager.allSourceFiles.sumOf {
            manager.getSourceMapEntries(it).size
        }.toLong().mustBe(expected, "source map entries in the program")
        manager.allSourceFiles.must(
            "every spelling and every fold target must be listed: missing " +
                ((folds.keys + folds.values) - manager.allSourceFiles.toSet()).map {
                    it.path
                },
        ) { containsAll(folds.keys + folds.values) }
        for ((raw, target) in folds) {
            if (raw == target) continue
            manager.getSourceMapEntries(
                raw,
            ).size.mustBe(0, "${raw.path} folded onto ${target.path} must keep no entries")
        }
    }

    /**
     * The query a listing field makes — "what line is this address in" — against a map of points.
     * Both halves have to hold: an entry sits at exactly the address the harvest gave it, and an
     * address mid-statement walks back to the statement it is inside
     * (`getSourceMapEntryIterator(addr, false)`, since a zero-length entry answers `getSourceMapEntries`
     * only at its own address).
     *
     * Addresses outside a defined block are excluded — those are the entries the applier reports
     * dropping, so including them would assert that a reported failure did not happen.
     */
    @Test
    fun addressesResolveToTheirEntries() {
        val manager = program.sourceFileManager
        // Folded: that is the identity the entries were transferred onto.
        val entries = artifacts.index.functions.flatMap { it.lineEntries }
            .filter { program.memory.getBlock(it.addr) != null }
        assumeTrue(entries.isNotEmpty(), "Skipping: no N_SLINE entries in this binary")

        val missing = entries.filterNot { e ->
            manager.getSourceMapEntries(e.addr).any { it.sourceFile == e.source && it.lineNumber == e.line }
        }
        missing.take(5).map {
            "${it.source.filename}:${it.line} @ ${it.addr}"
        }.mustBeEmpty(
            "${missing.size} of ${entries.size} line entries are absent from the program at their own address",
        )

        // Every published address, so the predecessor of the gap really is a predecessor.
        val addresses = artifacts.harvest.lineEntries.values.asSequence().flatten()
            .map { it.addr }.filter { program.memory.getBlock(it) != null }.distinct().sorted().toList()
        val (statement, inside) = addresses.zipWithNext()
            .firstNotNullOfOrNull { (a, b) ->
                (b.offset - a.offset).takeIf { it > 1 && a.hasSameAddressSpace(b) }?.let { a to a.add(it / 2) }
            } ?: return
        manager.getSourceMapEntryIterator(
            inside,
            false,
        ).firstOrNull()?.baseAddress.mustBe(statement, "walking back from $inside, mid-statement")
    }

    /**
     * A root becomes directory transforms on the program, and [LocalSources] reads back through them —
     * with the guard that a file whose content disagrees with what the harvest filed there is not the
     * file this binary was built from, however well its path resolved.
     *
     * The tree is built to match one of the program's own recorded directories, so this exercises the
     * fixture's real spellings (drive letters, `c++` segments) rather than invented ones.
     */
    @Test
    fun sourceRootRegistersTransformsAndGuardsAgainstTheWrongTree(@TempDir root: Path) {
        val source = program.sourceFileManager.allSourceFiles
            .firstOrNull { it.path.count { c -> c == '/' } > 1 }
            ?: abort("Skipping: no recorded source with a directory")
        val recordedDir = source.path.removeSuffix(source.filename)
        val local = root.resolve(recordedDir.split('/').last { it.isNotEmpty() })
            .resolve(source.filename)
        local.parent.createDirectories()
        local.writeText("// 1\n// 2\nclass Widget {};\nclass Gadget {};\nclass Sprocket {};\n")

        program.applySourceRoots(listOf(root), context)

        // Three claims at least, or the file is not judged at all — one misfiled declaration must not
        // be able to discard a correctly mapped file.
        val claims = listOf(
            Type.Decl(3, "Widget"),
            Type.Decl(4, "Gadget"),
            Type.Decl(5, "Sprocket"),
        )
        val agreeing = LocalSources(program, context) { claims }
        agreeing[source].mustBe(local.toFile(), "transform should resolve to the local file")

        val disagreeing = LocalSources(program, context) { claims.map { it.copy(line = it.line + 30) } }
        disagreeing[source].mustBeNull("a file that does not carry the claim must be dropped")
        context.diagnostics.snapshotCounters().getOrDefault("source-root-mismatch", 0L).must(
            "the drop must be reported",
        ) { this > 0 }
    }

    /**
     * A static member function takes no `this`. The stabs flag it `?` in the method-block trailer,
     * and parsing that as pure-virtual made ClassBuilder treat every one as an instance method:
     * forced __thiscall, injected a phantom `<Class> *this`, and replaced the N_PSYM params with the
     * empty list the `f(ret)` signature carries.
     *
     * Every `STATIC`-flagged method the harvest resolved to an address. Two halves, because they
     * broke separately: the declared parameters must survive, and no `this` may be injected
     * alongside them. The second half only ever failed under auto-analysis, because the injection
     * is Ghidra's: the demangler cannot tell a static member from an instance one and applies
     * `__thiscall` to both. Hence the convention in the failure message — it is the diagnosis.
     */
    @Test
    fun staticMethodsTakeNoThis() {
        val statics = staticMethodsByMangledName()
        assumeTrue(statics.isNotEmpty(), "Skipping: no static member functions in this fixture")
        // A nullary static (`…Ev`, the Itanium spelling of an empty parameter list) has nothing to
        // lose, so only the ones the mangling says take arguments can show the params-replaced half.
        val stripped = statics.filterKeys { !it.endsWith("Ev") }.values
            .filter { f -> f.parameters.none { it.name != "this" && it.name != "__return_storage_ptr__" } }
            .filter { f -> f.parameters.any { it.name == "this" } }
        val injected = statics.values.filter { f -> f.parameters.any { it.name == "this" } }
        fun render(fs: Collection<Function>) = fs.map { f ->
            val params = f.parameters.joinToString { it.name }
            "[${f.callingConventionName}] ${f.parentNamespace.name}::${f.name}($params)"
        }
        assertAll(
            {
                render(stripped).take(10).mustBeEmpty(
                    "${stripped.size} of ${statics.size} static member functions kept only an injected " +
                        "`this` — their declared parameters were replaced",
                )
            },
            {
                render(
                    injected,
                ).take(
                    10,
                ).mustBeEmpty("${injected.size} of ${statics.size} static member functions were given a `this`")
            },
        )
    }

    /**
     * A class whose only Itanium symbols are static data members still lands in its real namespace.
     * `ensureClassNamespace` read the chain off a *method's* mangled name, so `std::ctype_base` —
     * which declares no member functions at all, only `alnum`/`alpha`/`digit`/… — fell back to the
     * source-form leaf and was built as a root-level `ctype_base`. Its members' linkage names
     * (`_ZNSt10ctype_base5alnumE`) carry the same chain.
     */
    @Test
    fun constantsOnlyClassLandsInItsNamespace() {
        val cls = program.symbolTable.getSymbols("ctype_base")
            .firstOrNull { it.symbolType == ghidra.program.model.symbol.SymbolType.CLASS }
        assumeTrue(cls != null, "Skipping: ctype_base class namespace absent")
        cls!!.parentNamespace.name.mustBe(
            "std",
            "ctype_base sits under '${cls.parentNamespace.getName(true)}' — the class's namespace " +
                "chain was not recovered from its static members' linkage names",
        )
    }

    /**
     * A 1-byte bool global occupies 1 byte, and its neighbor is reachable.
     *
     * Without `-gstabs+` gcc spells `bool` as an enum over False/True (`gcc/dbxout.c`), losing the
     * width; as a sizeof(int) enum it swallowed the three globals after it, so five of CryptoPP's
     * eight adjacent `g_has*` flags had no data of their own — `createData` returns the containing
     * item as a success, so nothing threw.
     */
    @Test
    fun adjacentBoolGlobalsEachOwnTheirByte() {
        val flags = listOf("_ZN8CryptoPP9g_hasISSEE", "_ZN8CryptoPP9g_hasSSE2E", "_ZN8CryptoPP10g_hasSSSE3E")
            .mapNotNull { n ->
                sequenceOf(n, "_$n").firstNotNullOfOrNull { program.symbolTable.getSymbols(it).firstOrNull() }
            }
        assumeTrue(flags.size == 3, "Skipping: CryptoPP g_has* flags absent")
        val sizes = flags.associate { s ->
            s.name to program.listing.getDataAt(s.address)?.let { "${it.dataType.name}(${it.length})" }
        }
        sizes.values.must("each bool flag should own exactly its own byte; got $sizes") {
            all { it != null && it.endsWith("(1)") }
        }
    }

    /**
     * A static data member gets the type its class declares. These carry no `G`/`S` address stab, so
     * `applyGlobalOrStatic` never sees them and they used to reach Ghidra as a demangler-named
     * address with auto-analysis's guess for a type. `FieldDecl.mangled` is the only link from the
     * member back to its symbol — and being a real name gcc wrote, it works where reconstructing a
     * spelling cannot: every one of these is a template or nested libstdc++ type.
     *
     * `std::string::npos` is `static const size_type npos;` — 4 bytes, and emphatically not
     * `undefined4`.
     */
    @Test
    fun staticDataMemberIsTypedFromItsDeclaration() {
        val sym = sequenceOf("_ZNSs4nposE", "__ZNSs4nposE").firstNotNullOfOrNull {
            program.symbolTable.getSymbols(it).firstOrNull()
        }
        assumeTrue(sym != null, "Skipping: std::string::npos not present")
        // Plain `-gstabs` (no `+`) on gcc 4.2.1 emits static members as the bare `name:type,0,0`
        // with no linkage name at all — `_ZNSs4nposE` appears 0 times in crypto_mi_test_gcc421 but
        // 37 times in its _fullstabs twin. There is then nothing to reconcile *from*, so this is a
        // property of the debug info, not of the importer: gate on the link actually being present.
        val declared = artifacts.harvest.types.values
            .mapNotNull { it.body as? TypeDecl.Struct }
            .flatMap { it.fields }
            .any { it.name == "npos" && it.mangled != null }
        assumeTrue(declared, "Skipping: this build's stabs carry no linkage name for npos")
        val dt = program.listing.getDataAt(sym!!.address)?.dataType
        dt.mustNotBeNull("no data applied at std::string::npos (${sym.address})")
        dt.mustNotBeA<Undefined>(
            "std::string::npos is ${dt!!.name} — the static member's declared type never reached it",
        )
        dt.length.mustBe(4, "std::string::npos should be 4 bytes, got ${dt.name}")
    }

    /**
     * A register local lands in the register its stab names. The number is the record's n_value —
     * `w:r(0,5)` carries no register in the descriptor — and `readTrailingReg()` used to return a
     * hardcoded 0, so every register local in every fixture was placed in dbx 0 = EAX. Nothing
     * caught it: `reglocal-unmapped-regnum` can't fire when the number is always mappable.
     *
     * Checked over every register local the harvest recorded, so no fixture has to declare a
     * particular function. Ghidra narrows the storage to the variable's own width (a 2-byte local in
     * EDI is stored as `DI`), so the assertion is on the containing register, not the exact spelling.
     * Register locals shadowing a parameter name never reach the program (`reglocal-skipped-dup-param`)
     * and simply do not appear in the map being compared.
     */
    @Test
    fun registerLocalsUseTheirStabsRegister() {
        val declared = artifacts.harvest.functions.flatMap { func ->
            // Only names that occur once in the function. gcc emits one record per lexical block, so a
            // function can declare `__s1` twice in two blocks and hold it in a different register each
            // time (`_M_mutate` does exactly that, EAX/EDX and back). There is no name to pair those
            // against a single Ghidra local by, and pairing both against the first match reports the
            // swap as two failures — 287 functions on crypto_mi_test alone.
            val once = func.locals.filter { it.body.location == VariableLocation.REGISTER }
                .groupBy { it.body.name }.filterValues { it.size == 1 }.values.map { it.single() }
            once.mapNotNull { local ->
                val want = dbxRegisterName(program.defaultPointerSize, local.rawValue.toInt())
                    ?: return@mapNotNull null
                Triple(func, local.body.name, want)
            }
        }
        assumeTrue(declared.isNotEmpty(), "Skipping: no mappable register locals in this fixture")

        val checked = declared.mapNotNull { (func, name, want) ->
            val applied = program.functionManager.getFunctionAt(func.addr)
                ?.localVariables
                // ambiguous on Ghidra's side too — nothing to pair against
                ?.singleOrNull { it.name == name && it.variableStorage.isRegisterStorage }
                ?: return@mapNotNull null
            val got = applied.variableStorage.registers.single()
            Triple("${func.name}:$name", want, generateSequence(got) { it.parentRegister }.map { it.name }.toList())
        }
        assumeTrue(checked.isNotEmpty(), "Skipping: no register local reached the program")
        val wrong = checked.filterNot { (_, want, got) -> want in got }
            .map { (where, want, got) -> "$where: stab says $want, applied to ${got.first()}" }
        wrong.take(10).mustBeEmpty(
            "${wrong.size} of ${checked.size} register locals ignored their stab's n_value " +
                "(all landing in one register means the number was lost)",
        )
    }

    /**
     * No symbol may carry a raw Itanium-mangled name inside a non-global namespace. The Cygwin PE
     * loader's own `__Z…` symbols live in the global namespace and are fine; a mangled leaf under
     * a class (`Image::_ZN5Image7fetch32Em`) is the fingerprint of a
     * name we set raw on a function symbol that a later demangle pass displaced —
     * `SetLabelPrimaryCmd` re-creates the displaced name as a label in the same namespace.
     */
    @Test
    fun noMangledNameInsideANamespace() {
        val offenders = program.symbolTable.symbolIterator.iterator().asSequence()
            .filter { isMangled(it.name) && !it.parentNamespace.isGlobal }
            .map { "${it.address} ${it.parentNamespace.getName(true)}::${it.name} (${it.symbolType})" }
            .take(20)
            .toList()
        offenders.mustBeEmpty(
            "Found ${offenders.size} mangled symbols inside a namespace (showing first 20):\n" +
                offenders.joinToString("\n") { "  $it" },
        )
    }

    /**
     * Every slot [ghistabs.harvest.HarvestIndex.byLocation] declares is filled, at the path it declared.
     *
     * That map *is* the contract: `TypeRegistry` seeds and materializes each group at exactly
     * `(location.category, location.name)`, so it is the pipeline's own statement of what the DTM
     * should contain — which makes this exact, with no name normalization and no re-derivation of
     * attribution or shortening. Three separate things can go wrong and each is reported on its own:
     *
     *  1. **The type never materialized.** gcc reuses local type ids inside BINCL blocks, so several
     *     distinct types canonicalize onto one [GlobalTypeId]; before 4b21a6c the loser of that
     *     collision was dropped and its name went with it.
     *  2. **It landed somewhere else.** Attribution and the content-hash dedup have to agree on one
     *     category, or `ClassBuilder` cannot find the type it just built.
     *  3. **It is an empty stub.** A group whose winner has a body must not resolve to a
     *     zero-component Structure — the whole group is then unusable however well it was filed.
     *  4. **Two slots resolved onto one type.** Then one of the two names is simply not in the DTM,
     *     which is how the BINCL collision in (1) actually shows itself: three unrelated classes on
     *     one id, one DataType, two names gone. Distinct slots keep distinct types — measured at
     *     zero across the corpus, so it is assertable as zero.
     */
    @Test
    fun everyDeclaredSlotIsFilledWhereItWasDeclared() {
        val slots = artifacts.index.byLocation
        assumeTrue(slots.isNotEmpty(), "Skipping: no located types in this fixture")

        val applied = slots.map { (location, located) ->
            Triple(location, located, artifacts.registry.dataTypeFor(located.type.id))
        }
        fun report(of: List<String>) = of.sorted().take(10)

        val absent = applied.filter { (_, _, dt) -> dt == null }
            .map { (location, located) -> "$location (winner ${located.type.id})" }
        val misfiled = applied.mapNotNull { (location, _, dt) ->
            dt?.takeIf { it.categoryPath != location.category }?.let { "$location materialized at ${it.pathName}" }
        }
        val merged = applied.filter { (_, _, dt) -> dt != null }
            .groupBy({ it.third }, { it.first })
            .filterValues { it.size > 1 }
            .map { (dt, locations) -> "${dt?.pathName} claimed by ${locations.sortedBy { l -> l.toString() }}" }
        val hollow = applied.mapNotNull { (location, located, dt) ->
            val declared = (located.type.body as? TypeDecl.Struct)?.hasMembers == true
            "$location is an empty ${dt?.javaClass?.simpleName}"
                .takeIf { declared && (dt as? Composite)?.numComponents == 0 }
        }
        // Enums are not Composites, so `hollow` cannot see them: a named enum that materialized as
        // an empty Structure, or as an Enum with no values, is the same defect in the other kind.
        // (`exprInstHasComponents` checked exactly this for one enum on one binary.)
        val flatEnums = applied.mapNotNull { (location, located, dt) ->
            val members = (located.type.body as? TypeDecl.Enum)?.members?.size ?: return@mapNotNull null
            "$location declares $members values, materialized as ${dt?.javaClass?.simpleName}"
                .takeIf { members > 0 && (dt as? Enum)?.count?.let { it > 0 } != true }
        }
        assertAll(
            { report(absent).mustBeEmpty("${absent.size} declared slots never materialized") },
            { report(misfiled).mustBeEmpty("${misfiled.size} slots materialized off their declared category") },
            { report(hollow).mustBeEmpty("${hollow.size} slots with a declared body are empty stubs") },
            { report(merged).mustBeEmpty("${merged.size} DataTypes are claimed by more than one slot") },
            {
                report(
                    flatEnums,
                ).mustBeEmpty("${flatEnums.size} declared enums materialized without their values")
            },
        )
    }

    /**
     * A derived class carries its base subobject. Either shape counts:
     *  - a named `_base_…` / `_vbase_…` component, when the base type resolved;
     *  - the struct's first own field at offset > 0, the base bytes left as bare Undefined1 — the
     *    explicit "don't pretend we know what's here" choice, taken when the base's own stabs body
     *    is absent (libstdc++ classes reached only through iosfwd's forward declaration).
     *
     * What must never happen is a class with a space-occupying base whose own first field starts at
     * 0: the base bytes are then neither named nor reserved, and every offset below is a lie.
     *
     * Empty bases are excluded — the empty-base optimization means a `sizeof == 1` base contributes
     * nothing and the derived class's own field really does start at 0.
     */
    @Test
    fun derivedClassesCarryTheirBaseSubobject() {
        val derived = builtClasses()
            .filter { (body, _) -> body.bases.any { it.offsetBits == 0L && occupiesSpace(it.type) } }
            .map { (_, dt) -> dt }
            .filter { it.numComponents > 0 }
        assumeTrue(derived.isNotEmpty(), "Skipping: no derived classes materialized in this fixture")

        // Defined components only: the reserved-as-Undefined1 shape has *no* component naming the
        // base, and Ghidra's autofill would otherwise present those bare bytes as own fields at 0.
        val flat = derived.filterNot { cls ->
            cls.definedComponents.let { own ->
                own.any { Itanium.isBaseField(it.fieldName.orEmpty()) } || (own.firstOrNull()?.offset ?: 1) > 0
            }
        }
        flat.map {
            it.pathName
        }.take(10).mustBeEmpty(
            "${flat.size} of ${derived.size} derived classes reflect no inheritance at all: " +
                "no base subobject component and their own first field at offset 0",
        )
    }

    /**
     * A `vftable` label names a function-pointer array, so the word it sits on must point into
     * executable memory — and the word one pointer earlier must not, being the `rtti` header.
     *
     * That is the Itanium address point, and finding it is the whole job: `_ZTV+2*ptr` for an
     * ordinary class but `_ZTV+3*ptr` where a virtual base pushes a vbase-offset word in front of
     * the header (`basic_ifstream` → `basic_istream` → virtual `basic_ios`, and anything deriving from it). Reading
     * the words rather than recomputing the offset is what makes this independent of the layout
     * decision under test.
     */
    @Test
    fun vftableLabelsSitOnTheAddressPoint() {
        val ptr = program.defaultPointerSize.toLong()
        val labels = program.symbolTable.symbolIterator.iterator().asSequence()
            .filter { Itanium.VFTABLE in it.name && program.memory.getBlock(it.address) != null }
            .map { it.address }.distinct().toList()
        assumeTrue(labels.isNotEmpty(), "Skipping: no vftable labels in this fixture")

        val bad = labels
            .filterNot { pointsIntoCode(it) && !pointsIntoCode(it.subtract(ptr)) }
            .map { "vftable at $it → ${wordAt(it)?.toString(16)}" }
        bad.take(10).mustBeEmpty(
            "${bad.size} of ${labels.size} vftable labels are not on the address point " +
                "(mislaid on the rtti or vbase-offset word)",
        )
    }

    /**
     * A typeinfo global keeps the demangled name as its primary. The stab spells it `_ZTI<class>`,
     * and `ensureStabLabel` must not promote that raw name over the `<class>::typeinfo` Ghidra's
     * demangler already put there.
     */
    @Test
    fun typeinfoGlobalsKeepTheirDemangledPrimary() {
        val demangled = program.symbolTable.getSymbols(Itanium.DEMANGLED_TYPEINFO)
            .filterNot { it.parentNamespace.isGlobal }
        assumeTrue(demangled.isNotEmpty(), "Skipping: no demangled typeinfo symbols in this fixture")
        val clobbered = demangled
            .map { program.symbolTable.getPrimarySymbol(it.address) }
            .filter { isMangled(it.name) }
            .map { "${it.address} ${it.name}" }
        clobbered.take(10).mustBeEmpty(
            "${clobbered.size} typeinfo globals have a mangled primary label — " +
                "the stab name clobbered the demangled one",
        )
    }

    @Test
    fun typeInfoBaseClassesNotLeftAsStubs() {
        // std::type_info and __cxxabiv1::__{class,si_class,vmi_class}_type_info are real libsupc++
        // classes with methods (__do_upcast, …) but no stabs, so the demangler leaves empty /Demangler
        // stubs. typeInfoLayout must give them the RttiStructs layout — no 0-component Structure may survive.
        assumeTrue(
            program.symbolTable.getNamespace(Itanium.ABI_NAMESPACE, null) != null,
            "Skipping: no __cxxabiv1 namespace (RTTI base classes absent from this binary)",
        )
        val names = setOf(
            Itanium.TYPE_INFO,
            Itanium.CLASS_TYPE_INFO,
            Itanium.SI_CLASS_TYPE_INFO,
            Itanium.VMI_CLASS_TYPE_INFO,
        )
        val stubs = program.dataTypeManager.allDataTypes.asSequence()
            .filterIsInstance<Structure>()
            .filter { it.name in names && it.numComponents == 0 }
            .map { it.pathName }
            .toList()
        stubs.mustBeEmpty("typeinfo base classes left as empty stubs: $stubs")
    }

    /**
     * A `:t` typedef of a primitive materializes to a primitive of the width its stab declares.
     * `unsigned int` arrives as `r(0,1);0;4294967295;`, and the failure was it reaching the DTM as a
     * second, structurally-empty copy racing the real one for the name.
     *
     * [TypeDecl.Range], not [TypeDecl.Builtin]: the parser only emits Builtin for negative-id
     * *references*, never as a named definition, so gating on it made this test unrunnable on every
     * fixture in the corpus. Range is what gcc writes for a named integer — 8 to 17 per fixture.
     *
     * Floats are excluded rather than checked: gcc's i386 `long double` occupies 12 bytes and
     * `_Decimal128` 16, while Ghidra's `longdouble` builtin is 8 in the x86 data organization. That
     * mismatch is Ghidra's type model, not something the import can fix, so asserting it would
     * report a permanent condition as a regression.
     */
    @Test
    fun primitiveTypedefsMaterializeAtTheirDeclaredWidth() {
        val primitives = artifacts.harvest.types.values
            .filter { it.name != null && it.body is TypeDecl.Range }
            .mapNotNull { ast -> ast.body.sizeBytes?.takeIf { it > 0 }?.let { ast to it } }
        assumeTrue(primitives.isNotEmpty(), "Skipping: no named integer typedefs in this fixture")

        val wrong = primitives.mapNotNull { (ast, width) ->
            when (val dt = artifacts.registry.dataTypeFor(ast.id)) {
                null -> "${ast.ghidraName} never materialized"

                else ->
                    "${ast.ghidraName} is ${dt.name} (${dt.length} bytes), stab declares $width"
                        .takeIf { dt.length.toLong() != width }
            }
        }.distinct()
        wrong.sorted().take(10).mustBeEmpty(
            "${wrong.size} named primitive typedefs did not materialize at their declared width",
        )
    }

    /**
     * Inject a `/Demangler/std/string` Structure stub by hand and verify
     * the analyzer's DemanglerReplacer substitutes our `/stabs/string`
     * typedef when re-run. Reproduces the GUI scenario where Ghidra's
     * demangler creates the stub on demand during signature application
     * (suppressed in our headless `demangleMangledLabels` invocation by
     * `setApplySignature(false)`, so the other `demanglerStringReplaced`
     * test trivially passes — there's no stub to replace).
     *
     * Uses [ImportArtifacts.registry] — the populated registry the
     * importer set at end-of-import. Constructing a fresh one would mean
     * either (a) re-running materializeAll (creates `.conflict`
     * duplicates that race other @Test methods under
     * @Execution(CONCURRENT)) or (b) leaving it empty (findByName always
     * returns null, and we can't test the substitution path at all).
     */
    @Test
    fun demanglerStringReplacedAfterStubInjection() {
        assumeTrue(harvestsStdString, "Skipping: this fixture's stabs declare no std::string")
        val typeRegistry = artifacts.registry
        val demanglerCat = CategoryPath("/Demangler/std")
        program.runTransaction("inject-demangler-stub") {
            program.dataTypeManager.createCategory(demanglerCat)
                .addDataType(
                    StructureDataType(
                        demanglerCat,
                        "string",
                        0,
                        program.dataTypeManager,
                    ),
                    DataTypeConflictHandler.KEEP_HANDLER,
                )
        }
        program.dataTypeManager.getDataType(
            demanglerCat,
            "string",
        ).mustNotBeNull("precondition: injected stub should exist")

        program.runTransaction("rerun-demangler-replacer") {
            DemanglerReplacer(context, typeRegistry).replace()
        }

        program.dataTypeManager.getDataType(
            demanglerCat,
            "string",
        ).mustBeNull("/Demangler/std/string should have been replaced by /stabs/string")
    }

    @Test
    fun demanglerStringReplaced() {
        assumeTrue(harvestsStdString, "Skipping: this fixture's stabs declare no std::string")
        val strings = program.dataTypeManager.allDataTypes.asSequence().filter { it.name == "string" }.toList()
        val goodString = strings.find { !it.categoryPath.path.startsWith("/Demangler") }
        goodString.mustNotBeNull("no non-Demangler `string` DataType: $strings")
        goodString!!.mustNot("`string` is zero-length: $goodString") { isZeroLength }
        strings.mustNot("/Demangler/string still present: $strings") {
            any { it.categoryPath.path.startsWith("/Demangler") }
        }
    }

    /**
     * gcc encodes void as a type explicitly defined as itself (`(x,y)=(x,y)`), which the parser
     * lowers to [TypeDecl.Void]. It must materialize to VoidDataType — never an empty-Structure
     * placeholder named `[<file>,N]` polluting demangled signatures. (A *bare* `name:t(x,y)` with
     * no `=` is a forward reference, not void, and legitimately becomes an incomplete Structure —
     * that case is not checked here.)
     */
    @Test
    fun voidSelfRefNotMaterialized() {
        // Reuse setUp's harvest; re-harvest only when the import produced none (no stabs).
        val harvest = artifacts.harvest
        val voidAsts = harvest.types.values.filter { it.body is TypeDecl.Void }
        assumeTrue(voidAsts.isNotEmpty(), "no gcc-void asts in this fixture's harvest")

        val leaked = voidAsts.mapNotNull { ast ->
            // A void ast must NOT materialize as a Structure under any category bearing its ghidraName.
            program.dataTypeManager.allDataTypes.asSequence()
                .filterIsInstance<Structure>()
                .firstOrNull { it.name == ast.ghidraName }
                ?.pathName
        }

        leaked.mustBeEmpty("gcc-void asts leaked as Structures: $leaked (out of ${voidAsts.size} void asts)")
    }

    /**
     * A class that inherits its vtable still gets a populated vftable. gcc marks none of an override
     * as virtual when the class declares no new ones — all `NORMAL`, no `~%` vptr marker — so an
     * `isPoly`-style gate skipped the whole class and it was annotated with nothing.
     *
     * The condition is [hasPolymorphicBaseSubobject] alone, because that is the predicate the fix
     * introduced and the one `Layout` branches on (`VfptrAction.SkipInheritedFromBase`): every class
     * it answers true for inherits a vfptr rather than getting its own, so each needs a
     * `<Name>_vftable` with slots to inherit. Narrowing it further — no own virtuals, no `~%` marker,
     * my paraphrase of the old test's comment — selected nothing on any fixture. Restores the
     * coverage of the former `cPackedSegListVtableAnnotated`, which only ever ran on one binary.
     */
    @Test
    fun classesInheritingAVtableAreStillAnnotated() {
        val vftables = filledVftables().associateBy { it.name.removeSuffix("_vftable") }
        val inheriting = artifacts.harvest.types.values.mapNotNull { it.asStruct() }
            .filter { (_, body) -> with(artifacts.index) { hasPolymorphicBaseSubobject(body) } }
            // Only classes that reached the DTM at all — a class with no type is [everyDeclaredSlot…]'s.
            .filter { (ast, _) -> artifacts.registry.dataTypeFor(ast.id) != null }
        assumeTrue(inheriting.isNotEmpty(), "Skipping: no class inherits a vtable in this fixture")

        // Only classes the binary emitted a vtable *for*. One that inherits a vtable and overrides
        // nothing shares its base's and legitimately has no `<Name>_vftable` of its own — 51 of the
        // 2092 on locale_test are exactly that (`basic_ios`, `__codecvt_abstract_base`, the abstract
        // bases). A `_ZTV<class>` symbol is the binary saying this class has a distinct one.
        val withOwnVtable = inheriting.filter { (ast, _) ->
            Itanium.ztvCandidates(ast.ghidraName).any { program.symbolTable.getSymbols(it).firstOrNull() != null }
        }
        assumeTrue(withOwnVtable.isNotEmpty(), "Skipping: no inheriting class has its own vtable symbol")
        val bare = withOwnVtable.filter { (ast, _) -> ast.ghidraName !in vftables }.map { (ast, _) -> ast.ghidraName }
        bare.distinct().sorted().take(10).mustBeEmpty(
            "${bare.size} of ${withOwnVtable.size} classes with their own vtable inherit a vfptr " +
                "but have no populated vftable",
        )
    }

    @Test
    @ExpectedToFail(
        fixtures = [
            "crypto_mi_test_gcc421.exe", "crypto_mi_test_gcc421_stripped.exe",
            "xmltest_gcc421.exe", "xmltest_gcc421_stripped.exe",
            // a.out: both fixtures are plain C, so there are no classes and no vtables at all.
            "hello_aout_gcc295.o", "zlib_aout_gcc263.o",
            // C++, but gcc 2.95's minimal-debug `##` method encoding fails the class body, and its
            // vtables are pre-Itanium `__vt_9TiXmlNode` symbols rather than `_ZTV` regardless.
            "tinyxml_aout_gcc295.o",
        ],
        reason = "gcc 12 omits the method stab section for polymorphic classes, so no vftable is applied",
    )
    fun atLeastOneVtableStructApplied() {
        // box2d_tests shows no detectable C++ surface (no mangled symbols, no `_vptr`, no virtuals);
        // xmltest is C++ but gcc 12 omits the method section from the stab for every polymorphic
        // class (XMLNode et al.) — same Pattern-B family as the other gcc 12 missing-stab issues.
        // Surface via println so future fixture changes regain coverage without flagging the run.
        //
        // The applied vtable struct is the `<Class>_vftable` (the function-pointer array laid at the
        // address point); there is no separate `<Class>_vtable` full-record struct — the
        // offset_to_top + rtti header words are plain Data before the address point.
        val vftables = filledVftables()
        if (binaryName in setOf("box2d_tests", "xmltest")) {
            println("atLeastOneVtableStructApplied[$binaryName/$mode]: vftables=${vftables.size}")
            return
        }
        vftables.mustNotBeEmpty("Expected at least one *_vftable struct with components")
        // A derived class inherits its vfptr through its `_base_<Parent>` subobject, so most carry
        // no pointer directly — but the root of every chain must, or ClassBuilder's vfptr insertion
        // is broken end to end.
        val backEdges = vftables.count { vft ->
            program.dataTypeManager.allDataTypes.asSequence()
                .filterIsInstance<Structure>()
                .filter { it.name == vft.name.removeSuffix("_vftable") }
                .any { cls -> cls.components.any { (it.dataType as? Pointer)?.dataType === vft } }
        }

        backEdges.must(
            "Expected ≥ 1 *_vftable to have a back-edge {vfptr} from its class; got $backEdges / ${vftables.size}",
        ) { this >= 1 }
        // Every slot is a pointer to the function definition its own field is named for.
        val badSlots = vftables.flatMap { it.components.asIterable() }
            .filter { (it.dataType as? Pointer)?.dataType?.name != it.fieldName }
        badSlots.mustBeEmpty(
            "${badSlots.map { it.parent.name }.toSet()} have fields that aren't proper function " +
                "pointers: ${badSlots.map { it.dataType.name }.toSet()}",
        )
    }

    @Test
    @ExpectedToFail(
        fixtures = [
            "xmltest",
            "crypto_mi_test_gcc345.exe", "crypto_mi_test_gcc345_fullstabs.exe",
            "crypto_mi_test_gcc421.exe", "crypto_mi_test_gcc421_fullstabs.exe",
            "crypto_mi_test_gcc421_stripped.exe", "locale_test_gcc345_fullstabs.exe",
            "xmltest_gcc345.exe", "xmltest_gcc345_fullstabs.exe", "xmltest_gcc421.exe",
        ],
        reason = "unresolved empty /Demangler stubs — forward-declared RTTI/EH surface, not yet materialized",
    )
    fun demanglerHasNoEmptyStubs() {
        // /Demangler is the holding category for placeholder structs filled in by
        // DemanglerReplacer. After import these should all be resolved to real types
        // (length > 0 or absorbed into another category) — none should remain as empty
        // Structure stubs, except the bare-template/builtin artifacts with no concrete
        // type (see DemanglerWhitelist.ALLOWED).
        //
        // Only meaningful in AFTER. DemanglerReplacer runs in both modes (StabsImporter pass C),
        // but in CONCURRENT our analyzer fires alongside Ghidra's demangler and finishes before it
        // has created the /Demangler stubs, so replace() has nothing to replace yet (0 vs 169
        // `replaced-demangler`); the stubs are then created later and never revisited. That leaves
        // them empty at assertion time — a mode-ordering artifact, not a materialization gap.
        assumeTrue(mode == Mode.AFTER, "Skipping: /Demangler stubs are created after our pass in CONCURRENT")
        val allEmpty = program.dataTypeManager.allDataTypes
            .asSequence()
            .filterIsInstance<Structure>()
            .filter { it.categoryPath.path.startsWith("/Demangler") }
            .filter { it.isZeroLength || it.numComponents == 0 }
            .toList()
        // Dump the pre-whitelist empty-stub names so [DemanglerWhitelistAuditTest] can audit the whitelist
        // across the whole corpus — an entry live in no fixture is dead and should be pruned.
        emptyStubDumpFile.apply { parentFile.mkdirs() }
            .writeText(allEmpty.map { it.name }.toSortedSet().joinToString("\n"))
        // A `.conflict` fork is never whitelistable: the whitelist excuses names with no concrete
        // type to bind to, but a fork exists precisely *because* something already holds that name.
        // fewConflictRenames can't see these — one fork sits far under its 25-wide spike threshold.
        val forks = allEmpty.filter { DataTypeUtilities.isConflictDataTypeName(it.name) }.map { it.pathName }
        forks.sorted().mustBeEmpty("${forks.size} empty /Demangler .conflict forks")
        val emptyStubs = allEmpty
            .filterNot { it.name in DemanglerWhitelist.ALLOWED }
            .map { "${it.categoryPath.path}/${it.name}" }

        emptyStubs.mustBeEmpty("Expected zero unexpected empty /Demangler/* stubs, found ${emptyStubs.size}: ")
    }

    @Test
    fun fewConflictRenames() {
        // Ghidra forks a `.conflict` type when two distinct types collide on one (category, name).
        // Those renames should be the exception — a spike signals a canonicalization/dedup regression
        // like the cross-CU TypeId collision fixed in 4b21a6c. Reuses the production census
        // ([conflictCount], the `dtm-conflicts-created` source); corpus-wide it sits at 0.
        //
        // The earlier `^.+_\d+$` heuristic mismeasured badly: we never suffix names with `_N`, so it
        // caught gcc anonymous `$_N` aggregates and legitimately-numbered Win32 structs (JOB_INFO_1,
        // PRINTER_INFO_6, pulled in via mingw headers) — 250–920 "renames" for a real count of ~0.
        val conflicts = program.dataTypeManager.conflictCount()
        conflicts.must(
            "Suspiciously many .conflict-renamed types: $conflicts (expected < 25)",
        ) { this < 25 }
    }

    /**
     * Compatibility surface for `ApplyClassFunctionSignatureUpdatesScript` (shift-S) and
     * `RecoveredClassHelper`, over every vftable the import produced:
     *
     *  1. The vftable Structure lives under a CategoryPath containing the literal `"ClassDataTypes"`
     *     segment (the script tests
     *     `baseDataType.getCategoryPath().getPath().contains("ClassDataTypes")`).
     *  2. Its slots are typed function pointers (Pointer→FunctionDefinition), not generic
     *     `undefined4*`, so the decompiler resolves virtual calls and Ghidra creates the data refs
     *     the helper walks back from the virtual function.
     *
     * Half the slots, not all: an inherited slot whose method has no stab of its own stays untyped,
     * and how many of those a class has is a property of the binary.
     * ([vftableLabelsSitOnTheAddressPoint] covers the helper's third requirement, the `vftable`
     * symbol on the address point.)
     */
    @Test
    fun vftablesAreShiftSCompatible() {
        val vftables = filledVftables()
        assumeTrue(vftables.isNotEmpty(), "Skipping: no populated vftable in this fixture")

        val misfiled = vftables.filterNot { "ClassDataTypes" in it.categoryPath.path }.map { it.pathName }
        misfiled.take(
            10,
        ).mustBeEmpty("${misfiled.size} vftables sit outside ClassDataTypes (RecoveredClassHelper convention)")
        val untyped = vftables.filterNot { vft ->
            val typed = vft.components.count { (it.dataType as? Pointer)?.dataType is FunctionDefinition }
            typed > 0 && typed >= vft.numComponents / 2
        }.map { vft ->
            "${vft.name}: ${vft.components.count { (it.dataType as? Pointer)?.dataType is FunctionDefinition }}" +
                "/${vft.numComponents} slots typed"
        }
        untyped.take(10).mustBeEmpty("${untyped.size} of ${vftables.size} vftables are mostly untyped slots")
    }

    /**
     * Every virtual the stabs declare for a class has a slot in its `<Class>_vftable` — inherited
     * ones included, which is what the four-deep inheritance chain in the original report exposed.
     */
    @Test
    fun declaredVirtualsAllGetAVftableSlot() {
        val slotsByClass = filledVftables().associate { vft ->
            vft.name.removeSuffix("_vftable") to vft.components.mapNotNull { it.fieldName }.toSet()
        }
        assumeTrue(slotsByClass.isNotEmpty(), "Skipping: no populated vftable in this fixture")

        val missing = artifacts.harvest.types.values.mapNotNull { it.asStruct() }
            .mapNotNull { (ast, body) ->
                val slots = slotsByClass[ast.ghidraName] ?: return@mapNotNull null
                val virtuals = body.methods.filter { it.virt == VirtKind.VIRTUAL }.map { it.name }.toSet()
                (virtuals - slots).takeIf { it.isNotEmpty() }?.let { "${ast.ghidraName} missing $it" }
            }
        missing.sorted().take(10).mustBeEmpty("${missing.size} classes have declared virtuals with no vftable slot")
    }

    @Test
    @ExpectedToFail(
        fixtures = ["tinyxml_aout_gcc295.o"],
        reason = "single translation unit whose file-scope data happens to include no pointer global",
    )
    fun globalsCoverEachDataTypeKind() {
        val seenKinds = mutableSetOf<String>()
        program.listing.getDefinedData(true).forEach { data ->
            seenKinds += when (data.dataType) {
                is Structure -> "Structure"
                is Array -> "Array"
                is Union -> "Union"
                is Pointer -> "Pointer"
                is Enum -> "Enum"
                is TypeDef -> "TypeDef"
                is FunctionDefinition -> "FunctionDefinition"
                else -> "Primitive"
            }
        }
        // Enum is not required: a fixture may have no enum-typed globals at all.
        // The other kinds reflect basic global-application coverage.
        val required = setOf("Structure", "Pointer", "Primitive")
        val missing = required - seenKinds
        missing.mustBeEmpty(
            "Missing DataType kinds in globals: $missing (saw: $seenKinds)",
        )
    }

    /**
     * Function-local (`V` descriptor) statics get a PLATE comment naming their enclosing function,
     * attributed via the harvest-time `currentFunction` — so the gate is the harvest carrying one,
     * not any particular fixture (box2d emits ~32: `once` in b2PairQueryCallback, `s_next` in
     * b2ValidateReplay, …).
     */
    @Test
    fun functionLocalStaticsGetEnclosingFunctionComment() {
        assumeTrue(
            artifacts.harvest.staticsByCu.values.flatten().any { it.body.scope == StaticScope.FUNCTION },
            "Skipping: no function-local (V) statics in this fixture",
        )
        val plated = context.diagnostics.snapshotCounters()["static-local-plate"] ?: 0L
        plated.must(
            "expected function-local (V) statics to get 'static local of <fn>' plate comments; got $plated",
        ) { this > 0 }
    }

    @OptIn(ExperimentalSerializationApi::class)
    @Test
    fun harvestTest() {
        // Reuse setUp's import artifacts; re-read / re-harvest only when it produced none (no stabs).
        // Harvest is a pure producer (no Program mutation), so the fallback needs no transaction.
        val records = artifacts.records
        dumpJson.encodeToStream(records, recordsFile.outputStream())

        val harvest = artifacts.harvest
        dumpJson.encodeToStream(harvest, harvestFile.outputStream())

        val classStructs = harvest.types.values
            .mapNotNull { it.asStruct() }
            .filter { (_, body) -> body.rawKind == AggrKind.CLASS }
            .toList()
        println("${classStructs.size} class structs")

        val emptyStructs = harvest.types.values
            .mapNotNull { it.asStruct() }
            .filter { (_, body) -> body.fields.isEmpty() && body.methods.isEmpty() }
            .toList()

        val index = artifacts.index
        val baseTypes =
            harvest.types.values.filter { it.id.source is SourceFile.CUSource && !it.body.isXRefTarget }.toList()
        val different = baseTypes
            .groupBy { index.content(it.body) }
            .mapKeys { (k, v) -> k to v.map { it.name }.toSet() }

        // Never print a LayoutContent: the worst expands to ~11k nodes, and the old `println(different)`
        // stringified one per map key across every content class. hashCode is memoized and O(1);
        // identity is all this diagnostic needs.
        println(layoutStats(index))
        println("base types: ${baseTypes.size} types in ${different.size} content classes")
        for ((k, asts) in different) {
            val (content, names) = k
            if (asts.size > 1 && names.contains(null)) {
                println("- [${content.expandedNodes}]")
                for (ast in asts.sortedBy { it.id.toString() }) {
                    println("       =>  ${ast.id} ${ast.ghidraName} [${index.content(ast.body).expandedNodes}]")
                }
            }
        }

        // Aspirational: box2d_tests pulls in vendored deps (imgui, stbtt,
        // GLFW) whose stab entries are incomplete — gcc 12 emits empty
        // Struct bodies for some headers. Report via println instead of
        // asserting.
        if (emptyStructs.isNotEmpty()) {
            println(
                "harvestTest[$binaryName/$mode]: ${emptyStructs.size} empty structs in harvest " +
                    "(${emptyStructs.take(5).map { (a, _) -> a.ghidraName }})",
            )
        }
    }

    /**
     * Size of the cached [ContentIndex.LayoutContent] graph, measured by identity so shared subgraphs
     * are counted once. `expanded` is what a structural walk (e.g. the generated toString) would visit —
     * memoized per node, so the *count* is O(nodes) even when the count itself is astronomical.
     */
    private fun layoutStats(index: ghistabs.harvest.HarvestIndex): String {
        val roots = index.contentCache.values
        val seen = java.util.Collections.newSetFromMap(
            java.util.IdentityHashMap<ContentIndex.LayoutContent, Boolean>(),
        )
        val order = ArrayList<ContentIndex.LayoutContent>()
        val stack = ArrayDeque(roots.toList())
        var dataCells = 0L
        var listObjs = 0L
        while (stack.isNotEmpty()) {
            val n = stack.removeLast()
            if (!seen.add(n)) continue
            order += n
            dataCells += n.data.size
            listObjs += 1 + n.children.size
            n.children.forEach { stack.addAll(it) }
        }
        val worst = order.maxOfOrNull { it.expandedNodes } ?: 0
        val totalExpanded = roots.sumOf { it.expandedNodes.toLong() }
        // ~32B object + ArrayList(data) + ArrayList(children) + one inner ArrayList each, + boxed longs.
        val bytes = seen.size * 32L + listObjs * 40L + dataCells * 20L
        return "layout: distinctNodes=${seen.size} roots=${roots.size} dataCells=$dataCells " +
            "~${bytes / 1024 / 1024}MB | expanded(total)=$totalExpanded worstSingleNode=$worst"
    }

    // ---- Mangling / execution-order assertions, shared between modes. ----

    /**
     * A function's stab params reach it. The lookup in [ghistabs.importer.StabsImporter] is by
     * address, not by name, so it must succeed whether or not the symbol has been demangled yet —
     * i.e. in both modes. Checked over every free function whose stabs declare stack params and
     * whose Ghidra function was resolved; a class method's `this` is Ghidra's to inject, so those
     * are counted separately by [staticMethodsTakeNoThis] and the thiscall checks.
     */
    @Test
    fun stabParamsReachTheirFunctions() {
        // BEFORE runs without autoanalysis, so Ghidra has no frame for the applier to place into.
        assumeTrue { mode != Mode.BEFORE }
        val declared = artifacts.harvest.functions
            .filter { func -> func.params.any { it.body.name != "this" } }
            .mapNotNull { func ->
                val applied = program.functionManager.getFunctionAt(func.addr) ?: return@mapNotNull null
                applied.takeIf { it.parentNamespace.isGlobal }?.let { func to it }
            }
        assumeTrue(declared.isNotEmpty(), "Skipping: no free function with stab params resolved here")

        // `this` is excluded throughout: pre-Itanium gcc spells it as an ordinary leading parameter,
        // and whether it survives as a parameter at all is the calling convention's business — see
        // [mingwClassMethodsCarryThiscall].
        fun declaredNames(func: ghistabs.harvest.Func) = func.params.map { it.body.name }.filterNot { it == "this" }
        val lost = declared.filterNot { (func, applied) ->
            declaredNames(func).all { name -> applied.parameters.any { it.name == name } }
        }.map { (func, applied) ->
            "${func.name}: stabs name ${declaredNames(func)}, applied ${applied.parameters.map { it.name }}"
        }
        lost.take(10).mustBeEmpty("${lost.size} of ${declared.size} functions lost stab parameters")
    }

    /**
     * A function the stabs name with a mangled symbol comes out demangled. Ghidra's demangler runs
     * once at priority ~897 over loader-added symbols; the raw mangled names we set from the stabs
     * (in `applyAllFunctions`) appear later and would be missed, so
     * [ghistabs.importer.DemanglerReplacer.demangleMangledLabels] sweeps every IMPORTED `_Z` / `__Z`
     * symbol at the end of the import, with signature and calling-convention application disabled so
     * our stab-derived prototype and `__thiscall` choice still win.
     *
     * Per function against the harvest, not a share of the corpus: the gate is whether Ghidra's own
     * demangler can parse the name at all ([ghistabs.harvest.Func.demangledName], the same
     * `GnuDemangler`), so a mangling it genuinely cannot read is excluded rather than tolerated by a
     * threshold. What is left is exactly the sweep's contract.
     */
    @Test
    fun mangledFunctionNamesGetDemangled() {
        val demanglable = artifacts.harvest.functions
            .filter { isMangled(it.decl.name) }
            .mapNotNull { func -> program.functionManager.getFunctionAt(func.addr)?.let { func to it } }
        assumeTrue(demanglable.isNotEmpty(), "Skipping: no demanglable mangled functions in this fixture")

        val stillMangled = demanglable
            .filter { (func, applied) -> applied.name == func.decl.name }
            .map { (_, applied) -> "${applied.entryPoint} ${applied.name}" }
        stillMangled.sorted().take(10).mustBeEmpty(
            "${stillMangled.size} of ${demanglable.size} functions kept the raw mangled name the stab gave them",
        )
    }

    /**
     * `inheritance-applied` counter is only captured via CapturingSink in
     * AFTER mode (CONCURRENT mode feeds through MessageSinkAdapter→MessageLog).
     */
    @Test
    @ExpectedToFail(
        fixtures = [
            "hello_aout_gcc295.o", "zlib_aout_gcc263.o",
            // C++, but gcc 2.95 defaults to minimal debug, so every method reads `##<type>` — the
            // arguments live in the mangled name instead. The class body fails at the first one,
            // taking the `!` inheritance spec parsed just before it down with the record.
            "tinyxml_aout_gcc295.o",
        ],
        reason = "plain C fixtures — no C++ inheritance edges exist to materialize",
    )
    fun inheritanceWasApplied() {
        val applied = context.diagnostics.snapshotCounters()["inheritance-applied"] ?: 0L
        // box2d_tests has no detectable inheritance in our scan (no mangled
        // C++ symbols, no `_vptr`, no `~%`, no pseudo-field bitsize
        // anomalies — strings shows pure C). If a future build introduces
        // C++ paths, and we still get 0, this will surface in the run
        // output without flagging the test as failed.
        if (binaryName == "box2d_tests") {
            println("inheritanceWasApplied[$binaryName/$mode]: applied=$applied")
            return
        }
        applied.must(
            "Expected inheritance-applied counter > 0, got $applied (no C++ inheritance edges were materialized)",
        ) { this > 0 }
    }

    /**
     * No class method should end up with two `this` parameters. The
     * historical regression (see ClassBuilder comment around the
     * `ghidraInjectsThis` decision) was the importer keeping the stab's
     * explicit leading `this` while Ghidra's `__thiscall` convention also
     * auto-injected one, producing
     *   `void bouniaf::Dump(bouniaf *this, ushort this, …)`
     * Static class methods legitimately have zero `this` params, so the
     * tight bound is `count <= 1`, not `== 1`.
     */
    @Test
    fun classMethodsHaveAtMostOneThis() {
        val offenders = program.functions
            .filter { it.isMethod }
            .filter { f -> f.parameters.count { it.name == "this" } > 1 }
            .map { f ->
                val params = f.parameters.joinToString(", ") { "${it.name}: ${it.dataType.name}" }
                "${f.parentNamespace.name}::${f.name} cc=${f.callingConventionName} params=[$params]"
            }
            .take(20)
            .toList()
        offenders.mustBeEmpty(
            "Class methods must have at most one `this` (no duplicate-this regression): " +
                "${offenders.size} offenders:\n  - " + offenders.joinToString("\n  - "),
        )
    }

    /**
     * Any DataType we registered in the DTM with a name that's a serialized
     * GlobalTypeId (`[<source>,<n>]` shape) is an anonymous type we couldn't
     * give a meaningful name to. That's a missing name-promotion / fallback
     * path. Reading the listing, the user would see `[/xml/tinyxml2.cpp,42] *`
     * as a field type — not useful. Flag every one and fail.
     */
    @Test
    fun noAnonymousMaterializedTypes() {
        // [source,n] where source may contain '/', '#', '.', etc. — match liberally.
        val idLike = Regex("""^\[[^\[\]]+,\d+]$""")
        val anon = program.dataTypeManager.allDataTypes.asSequence()
            .filter { idLike.matches(it.name) }
            .take(20)
            .map { "${it.categoryPath}/${it.name} (${it::class.simpleName})" }
            .toList()
        // Aspirational: orphan-stub cleanup removes the empty ones, but
        // anonymous types referenced by other types stay (FunctionDefinition
        // params, struct field types, etc.). Their existence isn't a bug
        // per se — they're real anonymous aggregates from the source — but
        // the synthetic name is ugly. Report via println.
        if (anon.isNotEmpty()) {
            println(
                "noAnonymousMaterializedTypes[$binaryName/$mode]: ${anon.size} anonymous DTM types:\n  - " +
                    anon.joinToString("\n  - "),
            )
        }
    }

    @Test
    fun mingwClassMethodsCarryThiscall() {
        assumeTrue(
            binaryName.endsWith(".exe"),
            "Skipping: __thiscall check only meaningful on mingw fixtures",
        )
        val classFuncs = program.functions
            .filter { it.isMethod }
            .toList()
        // reparentMethod only reaches setCallingConvention("__thiscall") for a method it can pin to
        // an address: either an in-TU N_FUN stab (works even stripped) or, absent that, the COFF
        // symtab. A fully-stripped binary loses the symtab path, and the remaining out-of-line/inline
        // STL methods have no body here at all (non-stripped fullstabs shows the same ~991 resolve
        // failures) — so no class-namespaced function survives to tag. Nothing to assert then; but a
        // non-empty classFuncs with zero __thiscall is still a real regression, so keep asserting.
        assumeTrue(
            classFuncs.isNotEmpty(),
            "Skipping: no resolvable class methods (stripped symtab + no in-TU method bodies)",
        )
        val thiscalled = classFuncs.filter { it.callingConventionName == "__thiscall" }
        // Only a stab-declared method is ours to tag, and that is what this half asserts. With none —
        // gcc 4.x emits no method entries at all — tagging is left to the demangler's `isThisCall`,
        // which decides by comparing detected parameters against the mangled name's and so answers
        // only after auto-analysis. That is a property of Ghidra and the binary, not of the import.
        val declaredMethods = artifacts.harvest.types.values.sumOf { it.asStruct()?.second?.methods?.size ?: 0 }
        if (declaredMethods > 0) {
            thiscalled.mustNotBeEmpty(
                "binary=$binaryName: ${classFuncs.size} class methods, none tagged __thiscall, " +
                    "though the stabs declare $declaredMethods (reparentMethod never tagged one)",
            )
        }
        // __thiscall is what makes Ghidra inject the leading `this`, and it must be the class's own
        // pointer — an `int *this` left over from the register-storage guess means the convention
        // was set on a function whose class type never resolved.
        // By name, not position: a small-class return puts `__return_storage_ptr__` in front of `this`.
        val wrongThis = thiscalled.mapNotNull { f ->
            val self = f.parameters.firstOrNull { it.name == "this" } ?: return@mapNotNull null
            "${f.parentNamespace.name}::${f.name}(${self.dataType.name} this)"
                .takeUnless { (self.dataType as? Pointer)?.dataType?.name == f.parentNamespace.name }
        }
        wrongThis.take(10).mustBeEmpty(
            "${wrongThis.size} of ${thiscalled.size} __thiscall methods do not take their own class pointer",
        )
    }

    /**
     * Every field sits at the byte offset its stab declares, and spans the width it declares.
     *
     * The former `bouniafAndbouniafTruncated` pinned six of these by hand on one binary —
     * `LineNo` at +112, `Tok` at +168 spanning 24, `CurrentTok` at +192, `RecoverySet` at +236
     * spanning 40. Offsets are what make a layout usable at all, and once that test's fixture-named
     * assertions went, nothing checked them: a struct can be the right *length*
     * ([classesAreTruncatedToTheirLastDescribedByte]) with every field inside it in the wrong place.
     *
     * Excluded, because the two sides do not compare rather than because they are uninteresting:
     * bitfields (gcc numbers them in bits inside a storage unit, Ghidra as a component of the unit),
     * static members (no offset), and unions (every member at 0 by definition).
     *
     * Offsets only, not widths. A field's *span* is its type's materialized size, and
     * [classesAreTruncatedToTheirLastDescribedByte] deliberately truncates a class to its last
     * described byte — so a field typed by such a class spans less than the stab's `sizeBits` by
     * design (28 bytes against a declared 224 on cryptopp's policy holders). Asserting the declared
     * width would be asserting the opposite of the truncate.
     */
    @Test
    fun fieldsSitAtTheirDeclaredOffsets() {
        val checked = artifacts.index.byLocation.values.flatMap { located ->
            val body = located.type.body as? TypeDecl.Struct ?: return@flatMap emptyList()
            if (body.rawKind == AggrKind.UNION) return@flatMap emptyList()
            val dt = artifacts.registry.dataTypeFor(located.type.id) as? Structure ?: return@flatMap emptyList()
            val components = dt.components.associateBy { it.fieldName }
            body.fields
                .filterNot { it.isStatic }
                .filter { it.offsetBits % 8 == 0L && it.sizeBits % 8 == 0L && it.sizeBits > 0 }
                .mapNotNull { field -> components[field.name]?.let { Triple(dt, field, it) } }
        }
        assumeTrue(checked.isNotEmpty(), "Skipping: no byte-aligned fields materialized in this fixture")

        val misplaced = checked
            .filter { (_, field, component) -> component.offset.toLong() != field.offsetBits / 8 }
            .map { (dt, field, c) -> "${dt.name}.${field.name} at +${c.offset}, stab says +${field.offsetBits / 8}" }
        assertAll(
            {
                misplaced.sorted().take(10).mustBeEmpty(
                    "${misplaced.size} of ${checked.size} fields are not at their declared offset",
                )
            },
        )
    }

    /**
     * A class is exactly as long as its layout describes. gcc's `s<size>` is routinely inconsistent
     * with the fields that follow it — one class in the original report declares 328 bytes for a
     * layout that ends at 192 — and the placeholder-truncate fix takes "last described byte" as the size. That
     * removes the unexplained tail and, more importantly, makes a base fit its derived class's gap
     * exactly, so the base placement needs no overwrite or synthesis.
     *
     * The truncate has to happen at placeholder-creation time for that to hold: a derived class's
     * base loop must see the already-truncated placeholder, whatever order the two materialize in.
     */
    @Test
    fun classesAreTruncatedToTheirLastDescribedByte() {
        val classes = artifacts.harvest.types.values.mapNotNull { it.asStruct() }
            .mapNotNull { (ast, _) -> artifacts.registry.dataTypeFor(ast.id) as? Structure }
            .filter { it.numComponents > 0 && !it.isZeroLength }
        assumeTrue(classes.isNotEmpty(), "Skipping: no classes materialized in this fixture")

        val padded = classes
            .filterNot { it.length == it.components.last().endOffset + 1 }
            .map { "${it.name}: length=${it.length}, layout ends at ${it.components.last().endOffset + 1}" }
        padded.take(10).mustBeEmpty(
            "${padded.size} of ${classes.size} classes carry bytes past their last described field",
        )

        // A single base at +0 is the *same* Structure instance as the base class, not a same-sized
        // synthetic standing in for it — that is what the truncate-at-placeholder-creation ordering
        // buys, and holding an ancestor instead means the base loop resolved the wrong link.
        //
        val synthetic = builtClasses().mapNotNull { (body, dt) ->
            val base = body.bases.singleOrNull()
                ?.takeIf { it.offsetBits == 0L && !it.isVirtual && occupiesSpace(it.type) }
                ?: return@mapNotNull null
            val baseType = (base.type as? TypeDecl.Ref)?.id?.let { artifacts.registry.dataTypeFor(it) }
                ?: return@mapNotNull null
            val field = dt.components.firstOrNull { Itanium.isBaseField(it.fieldName.orEmpty()) }
                ?: return@mapNotNull null
            "${dt.name}: base field is ${field.dataType.pathName}, base class is ${baseType.pathName}"
                .takeUnless { field.offset == 0 && field.dataType === baseType }
        }
        synthetic.take(10).mustBeEmpty(
            "${synthetic.size} single-base classes hold a stand-in rather than the base Structure itself",
        )
    }

    /**
     * FillerByteAnalyzer is the only source of [AlignmentDataType] in the pipeline, so a nonzero
     * count is exactly its hits. Runs on every fixture.
     * (Folded from the former FillerByteAnalyzerIntegrationTest — rides on setUp's autoanalysis.)
     */
    @Test
    fun fillerBytesCollapsedToAlignment() {
        assumeTrue { mode != Mode.BEFORE }
        val data = program.listing.getDefinedData(true)
        var runs = 0
        while (data.hasNext()) if (data.next().dataType is AlignmentDataType) runs++
        runs.must("FillerByteAnalyzer collapsed no padding in $binaryName") { this > 0 }
    }

    /**
     * The GAS jump-over-fill idiom must collapse too, not just plain NOP runs: an unconditional
     * forward JMP over the padding to the aligned boundary, NOPs behind it (`eb 0d 90…`). gas emits
     * it wherever the padded region is reachable by fallthrough, so the Alignment has to start on
     * the JMP opcode — otherwise the jump disassembles as live code in front of the padding.
     *
     * The sites are found by scanning the bytes for the idiom, independently of the listing the
     * analyzer wrote — so this is a cross-check of `FillerByteAnalyzer`, not a restatement of it.
     *
     * Padding *between* functions only. gas emits the same three bytes for `-falign-loops` inside a
     * live function body (box2d has 17 of those and no other kind), where the JMP is reached by
     * fallthrough and is the function's own control flow: collapsing it to data would punch a hole
     * through the instruction stream and cost the enclosing function its decompilation. Nothing the
     * analyzer should touch, so nothing this should demand.
     */
    @Test
    fun jumpOverFillCollapsedToAlignment() {
        assumeTrue { mode != Mode.BEFORE }
        val sites = program.memory.blocks
            .filter { it.isExecute && it.isInitialized }
            .flatMap { block ->
                val bytes = ByteArray(block.size.toInt()).also { block.getBytes(block.start, it) }
                bytes.indices
                    .filter { jumpOverFillAt(bytes, it, block.start.offset) }
                    .map { block.start.add(it.toLong()) }
            }
            .filter { program.functionManager.getFunctionContaining(it) == null }
        assumeTrue(sites.isNotEmpty(), "Skipping: no jump-over-fill idiom in $binaryName")

        val uncollapsed = sites.filterNot { program.listing.getDataAt(it)?.dataType is AlignmentDataType }
        uncollapsed.take(10)
            .mustBeEmpty("${uncollapsed.size} of ${sites.size} jump-over-fill runs were left uncollapsed")
    }

    // ---- Shared lookups for the corpus-wide assertions above. ----

    /**
     * Every class as it was actually built: the canonical group's *winner* body paired with the
     * Structure that body produced.
     *
     * Not `harvest.types`, which is every ast a CU ever emitted. A group folds definitions that
     * disagree, and pairing a loser's body with `dataTypeFor` compares two different declarations —
     * cryptopp defines `InvalidKeyLength` eight times (`Exception` in two CUs, `InvalidArgument` in
     * six) and `tagMONITORINFOEXA` both flat and derived, so a layout assertion driven that way
     * reports gcc's inconsistency as our defect.
     */
    private fun builtClasses(): List<Pair<TypeDecl.Struct<GlobalTypeId>, Structure>> =
        artifacts.index.byLocation.values.mapNotNull { located ->
            val body = located.type.body as? TypeDecl.Struct ?: return@mapNotNull null
            (artifacts.registry.dataTypeFor(located.type.id) as? Structure)?.let { body to it }
        }

    /** Every `<Class>_vftable` that got slots, one copy per name (the fullest). */
    private fun filledVftables() = program.dataTypeManager.allDataTypes.asSequence()
        .filterIsInstance<Structure>().filter { it.name.endsWith("_vftable") }
        .groupBy { it.name }.values.map { copies -> copies.maxBy { it.numComponents } }
        .filter { it.numComponents > 0 }

    /** The Ghidra function for each `STATIC`-flagged method the stabs name, keyed by linkage name.
     *  The Cygwin PE loader prefixes symbols with `_`, so both spellings are tried. */
    private fun staticMethodsByMangledName(): Map<String, Function> = artifacts.harvest.types.values
        .mapNotNull { it.asStruct() }
        .flatMap { (_, body) -> body.methods.filter { it.virt == VirtKind.STATIC }.mapNotNull { it.mangled } }
        .distinct()
        .mapNotNull { mangled ->
            sequenceOf(mangled, "_$mangled")
                .mapNotNull { program.symbolTable.getSymbols(it).firstOrNull() }
                .firstNotNullOfOrNull { program.functionManager.getFunctionAt(it.address) }
                ?.let { mangled to it }
        }.toMap()

    /** The gas idiom at [at]: `eb <n>` then n NOPs, landing on a 16-byte boundary. */
    private fun jumpOverFillAt(bytes: ByteArray, at: Int, blockStart: Long): Boolean {
        val skip = bytes.getOrNull(at + 1)?.toInt() ?: return false
        val end = at + 2 + skip
        return bytes[at] == 0xeb.toByte() &&
            skip in 1..14 &&
            end <= bytes.size &&
            (blockStart + end) % 16 == 0L &&
            (at + 2 until end).all { bytes[it] == 0x90.toByte() }
    }

    /** Whether a base contributes bytes. An empty class is `sizeof == 1` and the empty-base
     *  optimization drops it from the layout entirely; member *functions* do not make it occupy
     *  space, so [TypeDecl.Struct.hasMembers] is the wrong question here. */
    private fun occupiesSpace(base: TypeDecl<GlobalTypeId>) =
        (resolve(base) as? TypeDecl.Struct)?.let { it.sizeBytes > 1 } == true

    /** A [TypeDecl.Ref] followed to the harvest body it names; anything else unchanged. */
    private fun resolve(type: TypeDecl<GlobalTypeId>): TypeDecl<GlobalTypeId> =
        (type as? TypeDecl.Ref)?.let { artifacts.harvest.types[it.id]?.body } ?: type

    private val harvestsStdString
        get() = artifacts.harvest.types.values.any { it.ghidraName.startsWith("basic_string<") }

    private fun wordAt(a: Address): Long? = runCatching {
        if (program.defaultPointerSize == 8) program.memory.getLong(a) else program.memory.getInt(a).toLong()
    }.getOrNull()

    /** Whether the pointer stored at [a] targets executable memory — how the address point is told
     *  apart from the rtti / vbase-offset words in front of it. */
    private fun pointsIntoCode(a: Address) = wordAt(a)
        ?.takeIf { it != 0L }
        ?.let { program.addressFactory.defaultAddressSpace.getAddress(it) }
        ?.let { program.memory.getBlock(it)?.isExecute } == true

    /**
     * The function-relative address heuristic ([ghistabs.GenericAddressResolver.stabAddress]): every `N_SLINE`/`N_LBRAC`/`N_RBRAC`
     * record, resolved against its enclosing `N_FUN`, must land in executable memory. A value left
     * un-rebased resolves to a tiny address in no code block. Not asserted against the *enclosing*
     * function specifically — gcc clones ctors/dtors, so a stab function's line range legitimately
     * spans sibling clones. Runs on every fixture. (Folded from the former
     * FuncRelativeAddressIntegrationTest.)
     */
    @Test
    @ExpectedToFail(
        fixtures = ["zlib_aout_gcc263.o"],
        reason = "relocatable object (ld -r): sections all sit at 0 unrelocated, so stab values " +
            "cannot resolve into executable code",
    )
    fun funcRelativeAddressesLandInExecutableCode() {
        val resolver = program.defaultContext().resolver
        val reader = StabReader.fromProgram(program)
        assumeTrue(reader != null, "no .stab in $binaryName")

        var funcStart: Address? = null
        var checked = 0
        val notCode = mutableListOf<String>()
        for (rec in reader!!.physicalRecords()) {
            when (rec.type) {
                StabType.N_FUN ->
                    funcStart = rec.name.ifEmpty { null }?.let { resolver.buildAddress(rec.value) }

                StabType.N_SLINE, StabType.N_LBRAC, StabType.N_RBRAC -> {
                    val fs = funcStart ?: continue
                    val target = resolver.stabAddress(rec.value, fs)
                    checked++
                    if (program.memory.getBlock(target)?.isExecute != true) {
                        notCode += "${rec.type} @${rec.index} value=0x${rec.value.toString(16)} → $target (from $fs)"
                    }
                }

                else -> {}
            }
        }
        assumeTrue(checked > 0, "no func-relative records in $binaryName")
        notCode.mustBeEmpty(
            "func-relative stab values resolved outside executable code in $binaryName " +
                "(${notCode.size}/$checked):\n${notCode.take(20).joinToString("\n")}",
        )
    }
}
