import ghistabs.build.GHIDRA_JVM_ARGS
import ghistabs.build.ghidraInstallDir
import ghistabs.build.sourceSets
import kotlin.io.path.Path
import kotlin.io.path.relativeTo

val cliMain = "ghistabs.cli.MainKt"

// The CLI has its own source set so neither it nor clikt land on the main runtimeClasspath, which is
// what the extension zip's lib/ is built from.
val Project.cli get() = sourceSets["cli"]

// No `-Djdk.serialFilterFactory` unlike the test harness: HeadlessGhidraApplicationConfiguration
// installs Ghidra's factory itself, and setting both throws "filter factory already instantiated".
// ghistabs-log4j2.xml ships in the cli jar; LoggingInitialization resolves the property off the
// classpath, so Ghidra's own console appender never gets between the animation and the terminal.
val cliJvmargs = GHIDRA_JVM_ARGS +
    listOf("-Xmx2g", "--enable-native-access=ALL-UNNAMED", "-Dlog4j.configurationFile=ghistabs-log4j2.xml")

// Run the CLI in-process against the `cli` runtime classpath (Ghidra jars + main output + clikt).
// Pass args with `-Pargs="skeleton <binary> -d out"`.
tasks.register<JavaExec>("runCli") {
    group = "application"
    description = "Run the headless skeleton/decomp CLI ($cliMain)"
    dependsOn(cli.classesTaskName)
    classpath = cli.runtimeClasspath
    mainClass.set(cliMain)
    jvmArgs(cliJvmargs)
    args = providers.gradleProperty("args").getOrElse("").split(" ").filter { it.isNotEmpty() }
}

/**
 * Fat CLI JAR, contains all depenedencies except ghidra
 */
val cliJar = tasks.register<Jar>("cliJar") {
    description = "Generate the JAR for headless skeleton/decomp CLI"
    archiveBaseName.set("ghidra-stabs-cli")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(mapOf("Main-Class" to cliMain))
    }
    from(sourceSets["main"].output, cli.output)
    from(
        cli.runtimeClasspath.files.filter { !it.toPath().startsWith(ghidraInstallDir) }.mapNotNull {
            when {
                it.isDirectory -> it
                it.isFile -> zipTree(it)
                else -> null
            }
        },
    )
}.flatMap { it.archiveFile }

/**
 * Standalone launcher at `build/libs/ghidra-stabs` that runs the fat CLI JAR at `build/libs/ghidra-stabs.jar`
 * and builds the classpath with ghidra's jars
 */
val cliScript = tasks.register("cliScript") {
    group = "application"
    description = "Generate a standalone launcher script for the CLI at build/cli/ghidra-stabs"
    val script = layout.buildDirectory.dir("libs").map { it.file(("ghidra-stabs")) }
    val runtimeClasspath = cli.runtimeClasspath
    val ghidraRoot = ghidraInstallDir // resolved here: doLast must not capture the Project
    outputs.file(script)
    doLast {
        val ghidraJars = runtimeClasspath.files.filter { it.toPath().startsWith(ghidraRoot) }

        val classpath = ghidraJars
            .map { Path($$"$GHIDRA_INSTALL_DIR").resolve(it.toPath().relativeTo(ghidraRoot)) }
            .joinToString(":")

        script.get().asFile.apply {
            writeText(
                buildString {
                    appendLine("#!/bin/sh")
                    appendLine("# Generated by `gradle buildCli`. lib/ is self-contained.")
                    appendLine("GHIDRA_INSTALL_DIR=\"\${GHIDRA_INSTALL_DIR:-$ghidraRoot}\"")
                    appendLine($$"dir=$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)")
                    appendLine("exec java ${cliJvmargs.joinToString(" ")} \\")
                    appendLine($$"  -cp \"$dir/ghidra-stabs-cli.jar:$$classpath\" \\")
                    appendLine("  $cliMain \"$@\"")
                },
            )
            setExecutable(true)
        }
    }
}.map { it.outputs.files.singleFile }

tasks.register<Zip>("zipCli") {
    description = "Build CLI distribution zip"
    inputs.file(cliJar)
    inputs.file(cliScript)
    archiveFileName.set("ghistabs-cli.zip")
    destinationDirectory.set(layout.projectDirectory.dir("dist"))
    from(
        cliJar,
        cliScript,
    )
}
